# server :
	# g++ -g -std=c++11 main.cpp webserver.cpp epoller.cpp ./timer/timer.cpp -o server -lpthread
svtrr :
	g++ -g -std=c++11 main.cpp webserver.cpp epoller.cpp ./logs/log.cpp ./timer/timer.cpp -o svtrr -lpthread
clean :
	rm svtrr
